export const MOBILE_CHANGED = 'MOBILE_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const SELLER_LOGIN_ATTEMP = 'SELLER_LOGIN_ATTEMP';
export const SELLER_LOGIN_SUCCESS = 'SELLER_LOGIN_SUCCESS';
export const SELLER_LOGIN_FAIL = 'SELLER_LOGIN_FAIL';
